mailer:
  development:
    delivery_method: :smtp
    settings:
      :address:        smtp.gmail.com
      :domain:         localhost
      :port:           587
      :user_name:      tkinnel@gmail.com
      :password:       GC#R227oaWuZ^h9!#os5e5UUwZlG7zuB
      :authentication: :plain
